// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uteuwjirvwtnpitanbik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0ZXV3amlydnd0bnBpdGFuYmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODg3NTUsImV4cCI6MjA3Mzc2NDc1NX0.pZmNWfB6j_iogs47BsXPjPhfimXKfiajPW2ANpA2oB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});